### ISSUE TITLE
security token in url

### ISSUE THREAD

**Issue by jjb** [deadlyicon/deploy-hook-forker#6]
Would you be open to a PR to solve this?

----

# Problem

Random people on the internet can POST to my deploy-hook-forker and trick me into thinking my project has been deployed.

# Solution

Make an option to require a secret token in the URL, e.g.

`heroku config:add SECRET=a1b2c3d4 --app acme-deploy-hook-forker`

`heroku addons:add deployhooks:http --url=http://acme-deploy-hook-forker.herokuapp.com?secret=a1b2c3d4 --app acme-project`

**Comment by rmm5t** [comment]
@jjb As someone who relies on this project, and as long as it's an optional ENV var (for backwards compatibility), I think this would be a nice and quite reasonable enhancement.

**Comment by deadlyicon** [comment]
I would be open to this feature :)

**Comment by jjb** [comment]
done!
