### ISSUE TITLE
Can an instance ping itself?

### ISSUE THREAD

**Issue by jjb** [deadlyicon/deploy-hook-forker#7]
If so, I'll submit a PR with a note about this.

----

![image](https://cloud.githubusercontent.com/assets/6097/15374687/7751cd0a-1d19-11e6-98c8-4ecf41c8b3f9.png)

![image](https://cloud.githubusercontent.com/assets/6097/15374630/2386403e-1d19-11e6-91f2-6d573891894f.png)

**Comment by deadlyicon** [comment]
I'm not sure. What would this PR look like?

**Comment by jjb** [comment]
done!
